2025-10-04 00:39:17,513 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 00:44:04,813 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 00:44:11,515 [WARNING] django.request: Not Found: /
2025-10-04 00:44:11,621 [WARNING] django.request: Not Found: /favicon.ico
2025-10-04 21:14:37,572 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 21:15:25,880 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 21:20:56,279 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 21:21:01,419 [WARNING] django.request: Not Found: /
2025-10-04 21:21:01,480 [WARNING] django.request: Not Found: /favicon.ico
2025-10-04 21:26:48,688 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 21:26:52,000 [WARNING] django.request: Not Found: /
2025-10-04 21:28:14,054 [WARNING] django.request: Not Found: /docs
2025-10-04 21:30:49,253 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\urls.py changed, reloading.
2025-10-04 21:30:49,907 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 21:31:00,151 [WARNING] django.request: Not Found: /docs
2025-10-04 21:31:08,174 [WARNING] django.request: Not Found: /api/members/
2025-10-04 21:31:37,300 [WARNING] django.request: Not Found: /api/member/manager/
2025-10-04 21:31:45,875 [WARNING] django.request: Not Found: /api/members/
2025-10-04 22:00:39,420 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 22:00:39,969 [WARNING] django.request: Not Found: /
2025-10-04 22:03:20,025 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\admin.py changed, reloading.
2025-10-04 22:03:20,936 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 22:04:17,440 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\manager\admin.py changed, reloading.
2025-10-04 22:04:18,111 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 22:04:40,334 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\admin.py changed, reloading.
2025-10-04 22:04:41,033 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 22:06:36,820 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-04 22:06:37,537 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 22:12:45,387 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-04 22:12:46,331 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 22:24:13,969 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-04 22:24:14,843 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 22:27:06,826 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-04 22:27:07,510 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 23:17:59,316 [ERROR] django.request: Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework_simplejwt\views.py", line 46, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 75, in validate
    refresh = self.get_token(self.user)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 66, in get_token
    return cls.token_class.for_user(user)  # type: ignore
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework_simplejwt\tokens.py", line 227, in for_user
    user_id = getattr(user, api_settings.USER_ID_FIELD)
AttributeError: 'Member' object has no attribute 'id'. Did you mean: 'sid'?
2025-10-04 23:20:28,804 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-04 23:20:33,011 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-04 23:31:41,404 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-04 23:31:42,194 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 21:35:47,122 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 21:36:00,367 [WARNING] django.request: Not Found: /
2025-10-05 21:36:00,486 [WARNING] django.request: Not Found: /favicon.ico
2025-10-05 21:54:28,091 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\serializer.py changed, reloading.
2025-10-05 21:54:34,489 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 21:54:59,942 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\serializer.py changed, reloading.
2025-10-05 21:55:01,080 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 21:55:02,848 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\serializer.py changed, reloading.
2025-10-05 21:55:04,044 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 21:58:06,080 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\serializer.py changed, reloading.
2025-10-05 21:58:06,849 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 22:28:30,288 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\serializer.py changed, reloading.
2025-10-05 22:28:31,228 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 22:36:17,074 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\views.py changed, reloading.
2025-10-05 22:36:18,086 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 22:37:16,432 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\views.py changed, reloading.
2025-10-05 22:37:17,476 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 22:37:19,307 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\views.py changed, reloading.
2025-10-05 22:37:20,166 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 22:41:51,835 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\urls.py changed, reloading.
2025-10-05 22:41:52,807 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 22:44:23,184 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\urls.py changed, reloading.
2025-10-05 22:44:24,110 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 22:44:43,420 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\urls.py changed, reloading.
2025-10-05 22:44:44,277 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 23:00:34,139 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-05 23:00:35,670 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 23:06:58,093 [WARNING] members.models: 이미 존재하는 학번 또는 이메일입니다: 학번=202403510, 이메일=kimcj@naver.com
2025-10-05 23:06:58,501 [ERROR] django.request: Internal Server Error: /api/member/register/
Traceback (most recent call last):
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: MEMBER.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\models.py", line 36, in create_user
    user.save(using=self._db)
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: MEMBER.username

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\serializer.py", line 19, in create
    user = Member.objects.create_user(
        sid=validated_data['sid'],
    ...<2 lines>...
        password=validated_data['password']
    )
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\models.py", line 42, in create_user
    raise ValueError("이미 존재하는 학번 또는 이메일입니다.")
ValueError: 이미 존재하는 학번 또는 이메일입니다.
2025-10-05 23:08:33,866 [WARNING] members.models: 이미 존재하는 학번 또는 이메일입니다: 학번=202403530, 이메일=kimcj@naver.com
2025-10-05 23:08:33,914 [ERROR] django.request: Internal Server Error: /api/member/register/
Traceback (most recent call last):
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: MEMBER.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\models.py", line 36, in create_user
    user.save(using=self._db)
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: MEMBER.username

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\backend_env\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\serializer.py", line 19, in create
    user = Member.objects.create_user(
        sid=validated_data['sid'],
    ...<2 lines>...
        password=validated_data['password']
    )
  File "C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\models.py", line 42, in create_user
    raise ValueError("이미 존재하는 학번 또는 이메일입니다.")
ValueError: 이미 존재하는 학번 또는 이메일입니다.
2025-10-05 23:10:05,733 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\settings.py changed, reloading.
2025-10-05 23:10:06,837 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-05 23:14:14,158 [WARNING] members.models: 이미 존재하는 학번 또는 이메일입니다: 학번=202499999, 이메일=test@example.com
2025-10-05 23:20:58,452 [WARNING] members.models: 이미 존재하는 학번 또는 이메일입니다: 학번=202499999, 이메일=test@example.com
2025-10-05 23:26:20,213 [WARNING] members.models: 이미 존재하는 학번 또는 이메일입니다: 학번=202133333, 이메일=test@naver.com
2025-10-06 12:56:57,810 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 12:57:04,340 [WARNING] django.request: Not Found: /
2025-10-06 12:57:04,403 [WARNING] django.request: Not Found: /favicon.ico
2025-10-06 21:19:54,939 [WARNING] django.request: Bad Request: /api/member/register/
2025-10-06 21:27:04,291 [WARNING] django.request: Bad Request: /api/member/register/
2025-10-06 21:34:58,060 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\models.py changed, reloading.
2025-10-06 21:35:04,282 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 21:38:50,372 [WARNING] members.models: 이미 존재하는 학번 또는 이메일입니다: 학번=202403510, 이메일=kimcj@naver.com
2025-10-06 21:39:09,472 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\members\models.py changed, reloading.
2025-10-06 21:39:10,272 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 21:47:30,045 [WARNING] django.request: Bad Request: /api/member/register/
2025-10-06 21:52:06,799 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\config\urls.py changed, reloading.
2025-10-06 21:52:07,522 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 21:53:22,639 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\views.py changed, reloading.
2025-10-06 21:53:23,605 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 21:55:06,017 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\models.py changed, reloading.
2025-10-06 21:55:06,830 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 21:56:30,612 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\models.py changed, reloading.
2025-10-06 21:56:31,522 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 21:58:09,676 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\views.py changed, reloading.
2025-10-06 21:58:10,477 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 22:00:42,091 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\models.py changed, reloading.
2025-10-06 22:00:43,027 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 22:01:25,568 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\views.py changed, reloading.
2025-10-06 22:01:26,363 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 22:03:23,195 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\views.py changed, reloading.
2025-10-06 22:03:24,115 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 22:07:25,967 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\models.py changed, reloading.
2025-10-06 22:07:26,874 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 22:08:10,342 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\library\models.py changed, reloading.
2025-10-06 22:08:11,211 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 22:44:38,379 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\manager\views.py changed, reloading.
2025-10-06 22:44:39,121 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-06 22:49:49,387 [INFO] django.utils.autoreload: C:\Users\woals\바탕 화면\HUFS_UP_project\library_project\backend\manager\serializer.py changed, reloading.
2025-10-06 22:49:50,075 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-10-07 15:42:39,750 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
